In [1]:
import sys
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree, svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from xgboost import XGBClassifier
import pickle
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
import os
print(os.getcwd())


/Users/nikhildeka/Desktop/Hackathon q1/Sample data


In [3]:
df = pd.read_csv('/Users/nikhildeka/Desktop/Hackathon q1/Sample data/mldata.csv')

In [4]:
df

Logical quotient rating  hackathons  coding skills rating  \
0                           5           0                     6   
1                           7           6                     4   
2                           2           3                     9   
3                           2           6                     3   
4                           2           0                     3   
...                       ...         ...                   ...   
6896                        7           5                     6   
6897                        6           5                     1   
6898                        5           1                     6   
6899                        1           6                     4   
6900                        5           6                     2   

      public speaking points self-learning capability? Extra-courses did  \
0                          2                       yes                no   
1                          3                        no               yes   
2                          1                        no               yes   
3                          5                        no               yes   
4                          4                       yes                no   
...                      ...                       ...               ...   
6896                       2                       yes                no   
6897                       8                        no                no   
6898                       7                       yes                no   
6899                       6                        no                no   
6900                       5                        no               yes   

            certifications          workshops reading and writing skills  \
0     information security            testing                       poor   
1        shell programming            testing                  excellent   
2     information security            testing                  excellent   
3            r programming  database security                  excellent   
4            distro making   game development                  excellent   
...                    ...                ...                        ...   
6896     shell programming            hacking                       poor   
6897      machine learning            hacking                  excellent   
6898         distro making       data science                       poor   
6899       app development   game development                       poor   
6900  information security  database security                  excellent   

     memory capability score    Interested subjects   interested career area   \
0                       poor            programming                   testing   
1                     medium             Management          system developer   
2                       poor       data engineering  Business process analyst   
3                       poor               networks                   testing   
4                     medium   Software Engineering          system developer   
...                      ...                    ...                       ...   
6896                    poor   Software Engineering                   testing   
6897               excellent            programming                   testing   
6898                    poor                    IOT          system developer   
6899               excellent       data engineering                 developer   
6900                  medium  Computer Architecture                  security   

     Type of company want to settle in? Taken inputs from seniors or elders  \
0                                   BPA                                  no   
1                        Cloud Services                                 yes   
2                   product development                                 yes   
3     Testing and Maintainance Services                                 yes   
4      

Number Encoder

In [5]:
cols = df[["self-learning capability?", "Extra-courses did","Taken inputs from seniors or elders", "worked in teams ever?", "Introvert"]]
for i in cols:
    cleanup_nums = {i: {"yes": 1, "no": 0}}
    df = df.replace(cleanup_nums)
   

mycol = df[["reading and writing skills", "memory capability score"]]
for i in mycol:
    cleanup_nums = {i: {"poor": 0, "medium": 1, "excellent": 2}}
    df = df.replace(cleanup_nums)

/var/folders/13/qlllp6jj0pd1whwnnbcz8mv80000gn/T/ipykernel_3452/470547563.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(cleanup_nums)
/var/folders/13/qlllp6jj0pd1whwnnbcz8mv80000gn/T/ipykernel_3452/470547563.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(cleanup_nums)


Label Encoding

In [6]:
category_cols = df[['certifications', 'workshops', 'Interested subjects', 'interested career area ', 'Type of company want to settle in?', 
                    'Interested Type of Books']]
for i in category_cols:
    df[i] = df[i].astype('category')
    df[i + "_code"] = df[i].cat.codes


In [7]:
# Dummy Variable Encoding
df = pd.get_dummies(df, columns=["Management or Technical", "hard/smart worker"], prefix=["A", "B"])

In [8]:
df

Logical quotient rating  hackathons  coding skills rating  \
0                           5           0                     6   
1                           7           6                     4   
2                           2           3                     9   
3                           2           6                     3   
4                           2           0                     3   
...                       ...         ...                   ...   
6896                        7           5                     6   
6897                        6           5                     1   
6898                        5           1                     6   
6899                        1           6                     4   
6900                        5           6                     2   

      public speaking points  self-learning capability?  Extra-courses did  \
0                          2                          1                  0   
1                          3                          0                  1   
2                          1                          0                  1   
3                          5                          0                  1   
4                          4                          1                  0   
...                      ...                        ...                ...   
6896                       2                          1                  0   
6897                       8                          0                  0   
6898                       7                          1                  0   
6899                       6                          0                  0   
6900                       5                          0                  1   

            certifications          workshops  reading and writing skills  \
0     information security            testing                           0   
1        shell programming            testing                           2   
2     information security            testing                           2   
3            r programming  database security                           2   
4            distro making   game development                           2   
...                    ...                ...                         ...   
6896     shell programming            hacking                           0   
6897      machine learning            hacking                           2   
6898         distro making       data science                           0   
6899       app development   game development                           0   
6900  information security  database security                           2   

      memory capability score  ... certifications_code workshops_code  \
0                           0  ...                   4              6   
1                           1  ...                   8              6   
2                           0  ...                   4              6   
3                           0  ...                   7              2   
4                           1  ...                   1              3   
...                       ...  ...                 ...            ...   
6896                        0  ...                   8              4   
6897                        2  ...                   5              4   
6898                        0  ...                   1              1   
6899                        2  ...                   0              3   
6900                        1  ...                   4              2   

     Interested subjects_code  interested career area _code  \
0                           9                             5   
1                           2                             4   
2                           5                             0   
3                           7                             5   
4                           3                             4   
...                       ...                           ...   
6896                 

Model Building

In [9]:
feed = df[['Logical quotient rating', 'coding skills rating', 'hackathons', 'public speaking points', 'self-learning capability?','Extra-courses did', 
           'Taken inputs from seniors or elders', 'worked in teams ever?', 'Introvert', 'reading and writing skills', 'memory capability score',  
           'B_hard worker', 'B_smart worker', 'A_Management', 'A_Technical', 'Interested subjects_code', 'Interested Type of Books_code', 'certifications_code', 
           'workshops_code', 'Type of company want to settle in?_code',  'interested career area _code',
             'Suggested Job Role']]

In [10]:
#Trainig The MOdel
df_train_x = feed.drop('Suggested Job Role',axis = 1)
df_train_y = feed['Suggested Job Role']

In [11]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
y_encoded = label_encoder.fit_transform(df_train_y)


Train Test Split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df_train_x, y_encoded, test_size=0.20, random_state=42)

In [13]:
# models = {
#     "Decision Tree": tree.DecisionTreeClassifier(),
#     "SVM": svm.SVC(),
#     "Random Forest": RandomForestClassifier(n_estimators=100),
#     "XGBClassifier": XGBClassifier(random_state=42, learning_rate=0.02, n_estimators=300)
# }

# # Lists to store results
# model_names = []
# accuracy_list = []
# confusion_matrices = []
# classification_reports = []

# # Iterate over each model
# for name, model in models.items():
#     print(f"Training and evaluating {name}...")
    
#     # Train the model
#     model.fit(x_train, y_train)
    
#     # Predictions
#     y_pred_train = model.predict(x_train)
#     y_pred_test = model.predict(x_test)
    
#     # Evaluate on training data
#     train_accuracy = accuracy_score(y_train, y_pred_train)
    
#     # Evaluate on testing data
#     test_accuracy = accuracy_score(y_test, y_pred_test)
    
#     # Confusion matrix and classification report for test set
#     conf_matrix = confusion_matrix(y_test, y_pred_test)
#     class_report = classification_report(y_test, y_pred_test)
    
#     # Append results
#     model_names.append(name)
#     accuracy_list.append(test_accuracy)
#     confusion_matrices.append(conf_matrix)
#     classification_reports.append(class_report)
    
#     # Display results
#     print(f"{name} Performance:")
#     print(f"Training Accuracy: {train_accuracy:.4f}")
#     print(f"Testing Accuracy: {test_accuracy:.4f}")
#     print(f"Confusion Matrix:\n{conf_matrix}")
#     print(f"Classification Report:\n{class_report}")
#     print("-" * 50)

# # Summary of all models
# results_df = pd.DataFrame({
#     'Model': model_names,
#     'Test Accuracy': accuracy_list
# })

# print("\nSummary of Model Performance:")
# display(results_df.sort_values(by='Test Accuracy', ascending=False))


In [16]:
import os
import pickle
from sklearn import tree, svm
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

save_directory = os.path.join("pkl")

# Create the directory if it doesn't exist
os.makedirs(save_directory, exist_ok=True)

# Models to train
models = {
    "Decision Tree": tree.DecisionTreeClassifier(),
    "SVM": svm.SVC(),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "XGBClassifier": XGBClassifier(random_state=42, learning_rate=0.02, n_estimators=300)
}
model_names = []
accuracy_list = []
confusion_matrices = []
classification_reports = []

# Iterate over each model
for name, model in models.items():
    print(f"Training and evaluating {name}...")
    
    # Train the model (replace x_train, y_train, x_test, y_test with your actual data)
    model.fit(x_train, y_train)
    
    # Predictions
    y_pred_train = model.predict(x_train)
    y_pred_test = model.predict(x_test)
    
    # Evaluate on training data
    train_accuracy = accuracy_score(y_train, y_pred_train)
    
    # Evaluate on testing data
    test_accuracy = accuracy_score(y_test, y_pred_test)
    
    # Confusion matrix and classification report for test set
    conf_matrix = confusion_matrix(y_test, y_pred_test)
    class_report = classification_report(y_test, y_pred_test)
    
    # Append results
    model_names.append(name)
    accuracy_list.append(test_accuracy)
    confusion_matrices.append(conf_matrix)
    classification_reports.append(class_report)
    
    # Save the model and its evaluation metrics
    model_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_model.pkl")
    with open(model_filename, 'wb') as file:
        pickle.dump(model, file)

    # Save the confusion matrix to a pickle file
    cm_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_confusion_matrix.pkl")
    with open(cm_filename, 'wb') as file:
        pickle.dump(conf_matrix, file)
    
    # Save the classification report to a pickle file
    report_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_classification_report.pkl")
    with open(report_filename, 'wb') as file:
        pickle.dump(class_report, file)
    
    # Save the accuracy score to a pickle file
    accuracy_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_accuracy.pkl")
    with open(accuracy_filename, 'wb') as file:
        pickle.dump(test_accuracy, file)
    
    # Display results
    print(f"{name} Performance:")
    print(f"Training Accuracy: {train_accuracy:.4f}")
    print(f"Testing Accuracy: {test_accuracy:.4f}")
    print(f"Confusion Matrix:\n{conf_matrix}")
    print(f"Classification Report:\n{class_report}")
    print("-" * 50)

    

Training and evaluating Decision Tree...
Decision Tree Performance:
Training Accuracy: 1.0000
Testing Accuracy: 0.0891
Confusion Matrix:
[[11 12  8  9 11 15 12 10 12 11 13  8]
 [10  7  9  9  5  7 10 11 14  8  6  9]
 [13  8 12 10 15 12 11 12  8  5  9  8]
 [ 3 12 11  9 11  5  2 10  5  7 10 15]
 [10 12  9 13 13  7  7  8  6 13 15  8]
 [13  9  7  9 12  6  8  6 16 10 11  6]
 [ 7 13 12  7  9  6 19  6  9 13  9  6]
 [ 9 10  7  7 11 10 20 12 12  6  8  6]
 [ 7  6  8 14 10 14 10  9 10  8  7 11]
 [ 8  9  8  8 17  7  8 12  8  6 12  8]
 [ 8 11  4 11 13 12  8 12  9 15  8  8]
 [ 6  9  7 15 14  8 11 10 11  6  2 10]]
Classification Report:
              precision    recall  f1-score   support

           0       0.10      0.08      0.09       132
           1       0.06      0.07      0.06       105
           2       0.12      0.10      0.11       123
           3       0.07      0.09      0.08       100
           4       0.09      0.11      0.10       121
           5       0.06      0.05      0.05   

In [15]:
model_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_model.pkl")
with open(model_filename, 'wb') as file:
    pickle.dump(model, file)

    # Save the confusion matrix to a pickle file
    cm_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_confusion_matrix.pkl")
    with open(cm_filename, 'wb') as file:
        pickle.dump(conf_matrix, file)
    
    # Save the classification report to a pickle file
    report_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_classification_report.pkl")
    with open(report_filename, 'wb') as file:
        pickle.dump(class_report, file)
    
    # Save the accuracy score to a pickle file
    accuracy_filename = os.path.join(save_directory, f"{name.replace(' ', '_')}_accuracy.pkl")
    with open(accuracy_filename, 'wb') as file:
        pickle.dump(test_accuracy, file)

# Summary of all models
results_df = pd.DataFrame({
    'Model': model_names,
    'Test Accuracy': accuracy_list
})

print("\nSummary of Model Performance:")
display(results_df.sort_values(by='Test Accuracy', ascending=False))

# Save the summary DataFrame to a pickle file
summary_filename = os.path.join(save_directory, "model_performance_summary.pkl")
with open(summary_filename, 'wb') as file:
    pickle.dump(results_df, file)

print(f"\nAll models and evaluation metrics have been saved to the directory: {save_directory}")



Summary of Model Performance:


Model  Test Accuracy
0  Decision Tree       0.090514
1            SVM       0.083273
2  Random Forest       0.079652
3  XGBClassifier       0.078928


All models and evaluation metrics have been saved to the directory: pkl
